# Generated by Django 5.1.1 on 2024-10-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='viewed_ips',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
