# Generated by Django 5.1.1 on 2024-10-16 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersmodel', '0002_alter_customuser_managers_chat_invite_link_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
